# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
    workflow_dispatch:
        -
    push:
        branches: 
          - CORE-930-build-deploy-PR

    pull_request:
        branches: 
          - CORE-930-build-deploy-PR

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true      

jobs:
  Build:
        runs-on : 
        -  ubuntu-runner
        steps :
         - name: Run a multi-line script
           run: |
            echo Add other actions to build,
            echo test, and deploy your project.
