name: Workflow Event check

# Controls when the workflow will run
on:
  push:
        branches: 
          - CORE-930-build-deploy-PR

  pull_request:
        branches: 
          - CORE-930-build-deploy-PR

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
 
  build:
   
    runs-on: ubuntu-latest
      - name: Run a one-line script
        run: |
          echo Hello, world!
          echo Add other actions to build
