name: Workflow Event check

# Controls when the workflow will run
on:
  push:
        branches: 
          - CORE-930-build-deploy-PR

  pull_request:
        branches: 
          - CORE-930-build-deploy-PR

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
 
  build:
    runs-on: self-hosted
    steps:
    - name: Run a one-line script
      run: |
          echo 'Job is running on CORE-930-build-deploy-PR'
          sleep 10
          echo 'Job is running on CORE-930-build-deploy-PR'
  eventCheck:
    runs-on: self-hosted
    steps:
    - name: Run a one-line script
      run: |
         if [[ "${{ github.event.name }}" == "push" ]]; then
            echo "Current event was a push event"
          elif [[ "${{ github.event.name }}" == "pull_request" ]]; then
            echo "Current event was a pull request event"
          else
            echo "Current event was something else"
          fi
