name: Workflow Event check

# Controls when the workflow will run
on:
  push:
        branches: 
          - main

  pull_request:
        branches: 
          - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
 
  build:
    runs-on: self-hosted
    steps:
    - name: Run a one-line script
      run: |
          echo 'Job is running on main'
          sleep 10
          echo 'Job is running on main'
  eventCheck:
    runs-on: self-hosted
    needs : build
    steps:
    - name: Run a one-line script
      run: |
         if [[ "${{ github.event_name }}" == "push" ]]; then
            echo "event name is:" ${{ github.event_name }} 
          elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "Current event was a pull request event"
          else
            echo "Current event was something else"
          fi

    - name: checking temp directory
      run: |
       echo " printing temp directory"
       echo ${{ runner.temp }}

    - name: Clean up temporary files
      run: |
          rm -rf ${{ runner.temp }}
          echo "Temporary files cleaned up."
